CREATE TABLE IF NOT EXISTS Type
(
    TYPE_ID INT NOT NULL AUTO_INCREMENT,
    TYPE_NAME VARCHAR(255),
    PRIMARY KEY (TYPE_ID)
);

CREATE TABLE IF NOT EXISTS Operation
(
    OPERATION_ID INT NOT NULL AUTO_INCREMENT,
    TYPE_ID      INT,
    COST         DOUBLE,
    PRIMARY KEY (OPERATION_ID),
    FOREIGN KEY (TYPE_ID) REFERENCES Type (TYPE_ID)
);

CREATE TABLE IF NOT EXISTS User
(
    USER_ID      INT          NOT NULL AUTO_INCREMENT,
    USERNAME     VARCHAR(255) NOT NULL,
    PASSWORD     VARCHAR(255) NOT NULL,
    STATUS       BOOLEAN, -- flag in true for active, false for inactive
    BALANCE      DOUBLE,
    ROLES        VARCHAR(255),
    PRIMARY KEY (USER_ID)
);

CREATE TABLE IF NOT EXISTS Record
(
    RECORD_ID          INT NOT NULL AUTO_INCREMENT,
    USER_ID            INT,
    OPERATION_ID       INT,
    AMOUNT             DOUBLE,
    USER_BALANCE       DOUBLE,
    OPERATION_RESPONSE LONGTEXT,
    DATE TIMESTAMP,
    PRIMARY KEY (RECORD_ID),
    FOREIGN KEY (OPERATION_ID) REFERENCES Operation (OPERATION_ID),
    FOREIGN KEY (USER_ID) REFERENCES User (USER_ID)
);