INSERT INTO Type(TYPE_NAME) VALUES ('ADDITION');
INSERT INTO Type(TYPE_NAME) VALUES ('SUBSTRACTION');
INSERT INTO Type(TYPE_NAME) VALUES ('MULTIPLICATION');
INSERT INTO Type(TYPE_NAME) VALUES ('DIVISION');
INSERT INTO Type(TYPE_NAME) VALUES ('SQRT');
INSERT INTO Type(TYPE_NAME) VALUES ('RANDOM_STR');